### ISSUE TITLE
Feature Request: Export/Import Strings

### ISSUE THREAD

**Issue by calebweeks** [leewillis77/say-what#11]
Hi Lee,

Would you ever consider building an "Export/Import" feature into the "Say What?" plugin?

No worries if not! 

In my case, we use WooCommerce for some non-profit (donation-based) transactions and so I "translate" the strings using "Say What?" from "Order" and "Customer" to "Donation" and "Donor", etc.

There are currently 58 strings that I change to achieve this (Subscriptions, Emails, and the like).

I can (and do) export the wp_say_what_strings from the database using phpMyAdmin when setting up a new website, but if the plugin could achieve this, there's an extra trip saved.

Thanks for even considering and for making a plugin to make all this easy in the first place. It's been, for us, great work! :-)

**Comment by leewillis77** [comment]
Hi, 

If I did then it would likely be via a wp-cli command, or set of commands - would that be useful, or would you only really find it useful if there was an online UI?

I guess having a WP-CLI makes it easily automate-able, but importing a default set of database entries should be fairly straightforward anyway?

**Comment by calebweeks** [comment]
Hi Lee - thanks for a quick reply. :-) 

You know way more about this than I, so feel free to say, "It's not worth the trouble!"

You are right that importing a default set of database entries is definitely straightforward. It works great. 

Here are the steps I currently take: 
1. Install "Say What?" on new site
2. Visit the new site's phpMyAdmin via cPanel
3. Locate wp_say_what_strings in the database
4. Import default/previously saved "wp_say_what_strings.sql" to wp_say_what_strings there in phpMyAdmin.
5. Confirm successful import back in new site's WordPress Dashboard > Tools > Text changes

Here are the steps I could see being cool:
1. Install "Say What?" on new site
2. Import wp_say_what_strings.sql in WordPress Dashboard > Tools > Text Changes option somewhere (maybe a "Tab" like on the [Redirection] (https://wordpress.org/plugins/redirection/) plugin?).

You've done great work so far - the plugin is completely useful as it is and the importing in phpMyAdmin is not difficult! If you chose to introduce such a feature, I imagine you'd know (or figure out) the best way to do it whether via WP-CLI or another way.

Thanks again for reading (and considering) our suggestions like this one! :-)

**Comment by samediamba** [comment]
I second the idea to add an easy to use export feature. I guess this would make life easier for the non-techies... That said, I would also add a plus to the fact that the plugin is an amazing performer. Keep it up!

**Comment by leewillis77** [comment]
Hi; 

I just shipped version 1.3 that adds import/export support to CSV using WP-CLI - http://wp-cli.org/, So - if you have WP-CLI installed, and Say-What installed, then you can do the following:

```$ wp say-what export --format=csv > /tmp/exported-replacements.csv```

This will export all string replacements to a CSV file.  Then on another blog you can do:

```$ wp say-what import /tmp/exported-replacements.csv```

This might not be quite what you're looking for (There's no UI for "downloading" and "uploading"), but realistically it's probably as much as I'm likely to add. I'll happily consider a pull-request that adds a UI version of this if someone else has the time to put it together, but closing this for now as it's now *possible* by using WP-CLI.

**Comment by samediamba** [comment]
thanks willis. you are the best

On 3/21/15, Lee Willis <notifications@github.com> wrote:
> Hi;
>
> I just shipped version 1.3 that adds import/export support to CSV using
> WP-CLI - http://wp-cli.org/, So - if you have WP-CLI installed, and Say-What
> installed, then you can do the following:
>
> ```$ wp say-what export --format=csv > /tmp/exported-replacements.csv```
>
> This will export all string replacements to a CSV file.  Then on another
> blog you can do:
>
> ```$ wp say-what import /tmp/exported-replacements.csv```
>
> This might not be quite what you're looking for (There's no UI for
> "downloading" and "uploading"), but realistically it's probably as much as
> I'm likely to add. I'll happily consider a pull-request that adds a UI
> version of this if someone else has the time to put it together, but closing
> this for now as it's now *possible* by using WP-CLI.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/leewillis77/say-what/issues/11#issuecomment-84379304


-- 
--
Samedi Amba
Web Consultant,
Baraton, Kenya.

Phone: +254-710-128 496
