### ISSUE TITLE
nginx 502 Bad Gateway after save or delete

### ISSUE THREAD

**Issue by teohhanhui** [leewillis77/say-what#13]
I've spent hours trying to troubleshoot / fix this, but I've given up. Strangely, removing `die();` after `wp_redirect` makes it work correctly...

WordPress 4.1.1

**Comment by leewillis77** [comment]
Hi, 

The plugin as developed on nginx originally, and I never saw that (Although it's not what I'm using right now). Removing the die() definitely isn't the correct fix (Since that will potentially cause code that should not be executed to be executed). Is there anything strange / unusual in your nginx config?

**Comment by teohhanhui** [comment]
Yeah I figured it might not be your plugin, but I don't know what else
could be causing it.

I'm only using the default nginx config from
https://github.com/roots/bedrock-ansible

Hi,

The plugin as developed on nginx originally, and I never saw that (Although
it's not what I'm using right now). Removing the die() definitely isn't the
correct fix (Since that will potentially cause code that should not be
executed to be executed). Is there anything strange / unusual in your nginx
config?

—
Reply to this email directly or view it on GitHub
<https://github.com/leewillis77/say-what/issues/13#issuecomment-87199225>.

**Comment by teohhanhui** [comment]
I've figured out the problem. It's caused by a plugin that rewrites output... Specifically `add_theme_support('soil-clean-up');` from https://github.com/roots/soil

**Comment by teohhanhui** [comment]
Restarting nginx and php5-fpm seems to have fixed the problem.
