### ISSUE TITLE
Headers already sent message on plugin activation

### ISSUE THREAD

**Issue by navjotjsingh** [leewillis77/say-what#14]
I got this message on activating the plugin.

>The plugin generated 220 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Plugin version: 1.4
WP version: 4.2

**Comment by leewillis77** [comment]
Hi,

Thanks for the bug report. I'm aware of this warning, although it's pretty harmless. It only occurs the first time the plugin is activated, and is basically a race condition caused when the plugin tries to read from a database table before it is created. It won't cause any issues after that.

I expect to include a fix for it in the next release, but don't have a date for that yet. Happy to leave this open until then.
