### ISSUE TITLE
Translating _n()

### ISSUE THREAD

**Issue by JosVelasco** [leewillis77/say-what#15]
I'm not sure if the plugin supports the translation of this kind of functions:
![screen shot 2015-06-25 at 14 45 42](https://cloud.githubusercontent.com/assets/13054571/8364070/fe1d0396-1b48-11e5-950d-40f25d9bef8f.png)

**Comment by leewillis77** [comment]
It doesn't currently support the "n" functions. Definitely on the roadmap, but need to consider the impact on the UI and a nice way to support them without overcomplicating the common case.

**Comment by leewillis77** [comment]
Just a quick note here. The paid-version now supports this feature, and I'll merge it back into the free version when time allows:

https://plugins.leewillis.co.uk/downloads/say-what-pro/
