### ISSUE TITLE
WPML compatibility?

### ISSUE THREAD

**Issue by heinpoblome** [leewillis77/say-what#17]
Hi, 
any plans to make this incredible plugin WPML compatible?

Or, as an alternative, include a setting so that it takes into account a WPML installation. 

It seems that Say What? takes action 'before' WPML causing altered strings not to be translated anymore. They just show up as the altered strings. It would be great if the plugin detected WPML, and 'let translations pass' if you know what I mean.

**Comment by leewillis77** [comment]
Closing as duplicate of #6
