### ISSUE TITLE
say what! does not override language strings which are in the global WP language folder.

### ISSUE THREAD

**Issue by Tobias-Conrad** [leewillis77/say-what#18]
wp-content/languages/plugins

the bad thing if i alter the language file in the global WP language folder it gets auto overriden by the next wordpress.org language update.

so this is really urgent.

**Comment by leewillis77** [comment]
Hi Tobias;

I'm not sure exactly what you're having problems with - can you explain step by step?

**Comment by Tobias-Conrad** [comment]
Hi Lee Willis,

At the Moment i do a overwrite by po File in the Global language/Plugin folder. Because with your Plugin not working.

I found and entered the string in your Plugin but it does Exchange.
Maybe your Plugin do not overwrite Strings from language/Plugin folder po files. 

Maybe by Option would be nice.
Or you Look if you are overwrite the string. View the Status near the string in your Plugin. So User can be Sure it is working.

Mit freundlichen Grüßen 

Tobias Conrad 

Tobias Conrad 
An der Lohbek 6b 
22529 Hamburg 
040 71 66 87 86 
0321 21 40 38 65 FAX/AB 
0160 26 30 26 1 mobil 
tobiasconrad@leupus.de 

Ihr Technik Trainer 
www.leupus.de

**Comment by leewillis77** [comment]
Hi Tobias;

When you set up a replacement you have to use the **original** string, not the translated version - does that help?

**Comment by Tobias-Conrad** [comment]
No i am Sure i used the right English string. First Line in the po File.

Mit freundlichen Grüßen 

Tobias Conrad 

Tobias Conrad 
An der Lohbek 6b 
22529 Hamburg 
040 71 66 87 86 
0321 21 40 38 65 FAX/AB 
0160 26 30 26 1 mobil 
tobiasconrad@leupus.de 

Ihr Technik Trainer 
www.leupus.de

**Comment by leewillis77** [comment]
Hi Tobias; 

I'm pretty sure that everything is working as I'd expect. If you have the Pro version then you can raise a support request here http://plugins.leewillis.co.uk/support with your licence details and I'll happily take a more detailed look, but this looks like an issue with how you're using the plugin or something specific to your site, and not a bug in the plugin.
