### ISSUE TITLE
Issue when replacing string that contains &

### ISSUE THREAD

**Issue by vzani** [leewillis77/say-what#19]
Hello

I'm trying to replace the following string

_e('Billing & Shipping', 'woocommerce-multistep-checkout')

Source text Billing & Shipping, domain woocommerce-multistep-checkout
But it's not woking, I believe due to & character.

Others replacements works fine

**Comment by leewillis77** [comment]
Hi; 

The plugin can replace strings with "&" in just fine - I've just tested that locally and it works fine. The most likely cause for your replacement appearing not to work is that the string you're replacing isn't the one being used. I'd suggest contacting the authors of the relevant plugin for further advise on whether that text is controlled some other way (e.g. via a setting or similar).
