### ISSUE TITLE
Remove need for custom database table

### ISSUE THREAD

**Issue by leewillis77** [leewillis77/say-what#4]
Remove need for custom database table

**Comment by JJJ** [comment]
😬 I think the custom database table is OK in this instance.

As a separate issue, it would be great to cache the Settings database query:

https://github.com/leewillis77/say-what/blob/1815a6c797a3e3fab28c88f9f0ccb609b0b4f0d6/say-what-settings.php#L36

**Comment by leewillis77** [comment]
> I think the custom database table is OK in this instance.

Absolutely. 2022-me agrees. I'll close this - thanks for commenting and reminding me :)

> As a separate issue, it would be great to cache the Settings database query

Yeah. I think we'd actually cache the flattened array (only running the DB query if we needed to create that). We'd probably only want to cache it if there's a persistent cache in place. I'll open a separate issue for that - thanks for the nudge!
